import { Activity, ArrowRight, CalendarDays, Dumbbell, Flame, Scale, TrendingUp } from 'lucide-react';
import { useApp } from '../state/AppStore.jsx';
import { addDays, addMonths, number, prettyDay, stamp, today } from '../lib/dates.js';
import { chronological, workoutVolume } from '../lib/progress.js';
import { Empty, LinkButton, PageTitle, Stat } from '../components/UI.jsx';
import CompositionChart from '../components/CompositionChart.jsx';
import SupplementToggles from '../components/SupplementToggles.jsx';

export default function Dashboard() {
  const { data } = useApp();
  const now = today();
  const latest = [...data.metrics].sort((a, b) => b.date.localeCompare(a.date))[0];
  const latestMuscle = [...data.metrics].filter(m => m.muscle != null).sort((a, b) => b.date.localeCompare(a.date))[0];
  const workouts = [...data.workouts].sort((a, b) => chronological(b, a));
  const week = workouts.filter(w => w.date >= addDays(now, -6) && w.date <= now);
  const start = data.settings.programStart, end = addMonths(start, 6);
  const progress = Math.min(100, Math.max(0, (stamp(now) - stamp(start)) / (stamp(end) - stamp(start)) * 100));
  return <>
    <PageTitle title="Build strength. See progress." subtitle="Your training, your numbers, your next personal best." action={<LinkButton href="#/workouts/new">Log a workout</LinkButton>} />
    <div className="dashboard-hero"><section className="hero-card"><div className="hero-kicker"><span className="live-dot" />THE WORK ADDS UP</div><h2>One more rep.<br />A stronger you.</h2><p>Show up. Write it down. Watch the little wins become real progress.</p><a href="#/routines">Find today’s routine <ArrowRight size={17} /></a><div className="plate-art" aria-hidden="true"><div className="plate p3" /><div className="plate p2" /><div className="plate p1"><span>20<small>KG</small></span></div><div className="barbell-bar" /></div></section><section className="block-card"><div className="section-label"><CalendarDays size={17} /> YOUR SIX-MONTH BLOCK</div><h3>Play the long game.</h3><p>{prettyDay(start, { month: 'short', day: 'numeric', year: 'numeric' })} — {prettyDay(addDays(end, -1), { month: 'short', day: 'numeric', year: 'numeric' })}</p><div className="block-progress"><strong>{Math.round(progress)}<span>%</span></strong><small>{now < start ? 'Starts soon' : now >= end ? 'Block complete' : 'of the timeline'}</small></div><div className="progress-track" role="progressbar" aria-label="Six-month timeline elapsed" aria-valuenow={Math.round(progress)} aria-valuemin={0} aria-valuemax={100}><div style={{ width: `${progress}%` }} /></div><a href="#/settings">Adjust your training block <ArrowRight size={14} /></a></section></div>
    <div className="stat-grid"><Stat label="Training sessions" value={data.workouts.length} icon={Dumbbell} note={`${week.length} logged in the last 7 days`} /><Stat label="Weekly volume" value={number(week.reduce((sum, w) => sum + workoutVolume(w), 0), 0)} unit="kg·reps" icon={TrendingUp} note="Total logged load × reps, last 7 days" /><Stat label="Body weight" value={number(latest?.weight)} unit="kg" icon={Scale} note={latest ? `Last recorded ${prettyDay(latest.date)}` : 'Add your first measurement'} /><Stat label="Skeletal muscle" value={number(latestMuscle?.muscle)} unit="kg" icon={Activity} note={latestMuscle ? `Last recorded ${prettyDay(latestMuscle.date)}` : 'Record your measured muscle mass'} accent /></div>
    <div className="dashboard-grid"><section className="panel composition-panel"><div className="panel-heading"><div><p className="eyebrow">THE BIGGER PICTURE</p><h2>Body composition</h2></div><a className="text-link" href="#/metrics">View metrics <ArrowRight size={15} /></a></div><CompositionChart metrics={data.metrics} settings={data.settings} /></section><section className="panel daily-panel"><div className="panel-heading"><div><p className="eyebrow">CONSISTENCY COUNTS</p><h2>Your daily stack</h2></div><Flame size={21} className="accent-icon" /></div><div className="daily-date">{prettyDay(now, { weekday: 'long', month: 'short', day: 'numeric' })}</div><SupplementToggles date={now} /><div className="daily-note"><span className="dot muscle" />{['protein', 'creatine'].filter(k => data.supplements[now]?.[k]).length} of 2 logged today</div><a className="text-link" href="#/supplements">See your consistency <ArrowRight size={15} /></a></section></div>
    <section className="panel recent-panel"><div className="panel-heading"><div><p className="eyebrow">REPS IN THE BANK</p><h2>Recent sessions</h2></div><a className="text-link" href="#/workouts">All workouts <ArrowRight size={15} /></a></div>{workouts.length ? <div className="recent-list">{workouts.slice(0, 4).map(w => <a className="recent-row" key={w.id} href={`#/workouts/${encodeURIComponent(w.id)}`}><span className="recent-icon"><Dumbbell size={19} /></span><span className="recent-title"><strong>{w.title}</strong><small>{prettyDay(w.date)} · {w.exercises.length} exercises · {w.exercises.reduce((sum, e) => sum + e.sets.length, 0)} sets</small></span><span className="recent-volume">{number(workoutVolume(w), 0)}<small> kg·reps</small></span><ArrowRight size={16} /></a>)}</div> : <Empty icon={Dumbbell} title="Every strong story has a first session." action={<a className="btn btn-secondary" href="#/workouts/new">Log your first workout</a>}>Your recent workouts and lifting volume will appear here.</Empty>}</section>
  </>;
}
